# Generated by Django 3.0.1 on 2020-01-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota', models.CharField(choices=[('PE', 'perro'), ('GA', 'gato'), ('LO', 'loro')], max_length=2)),
                ('nombre', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'macho'), ('H', 'hembra')], max_length=2)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('edad_aproximada', models.IntegerField()),
                ('imagen', models.URLField(max_length=100)),
                ('detalles', models.CharField(max_length=200)),
                ('razas', models.ManyToManyField(to='Mascotas.Raza')),
            ],
        ),
    ]
