# Generated by Django 3.0.1 on 2020-01-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota', models.CharField(choices=[('PE', 'perro'), ('GA', 'gato'), ('LO', 'loro')], max_length=2)),
                ('nombre', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'macho'), ('H', 'hembra')], max_length=2)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('edad_aproximada', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imagen', models.URLField(max_length=100)),
                ('detalles', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaPerdidaEncontrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_mascota', models.CharField(choices=[('PE', 'perdido'), ('EN', 'encontrado')], max_length=2)),
                ('sector_encuentro_perdida', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=300)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Mascota')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_usuarios.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaEnAdopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_juego', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Mascota')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_usuarios.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaAdoptada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalle', models.CharField(max_length=200)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Mascota')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_usuarios.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='razas',
            field=models.ManyToManyField(to='Mascotas.Raza'),
        ),
    ]
