# Generated by Django 3.0.1 on 2020-01-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotaadoptada',
            name='hora',
        ),
    ]
