# Generated by Django 3.0.2 on 2020-01-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0002_auto_20200112_1443'),
        ('Mascotas', '0002_auto_20200111_2136'),
    ]

    operations = [
    ]
