# Generated by Django 3.0.1 on 2020-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0002_remove_mascotaadoptada_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotaperdidaencontrada',
            name='estado_mascota',
            field=models.CharField(choices=[('PE', 'perdido'), ('EN', 'encontrado'), ('CO', 'completo')], max_length=2),
        ),
    ]
